---
- hosts: all
  sudo: yes

  tasks:

    - name: Add the goland repo
      apt_repository: repo='ppa:gophers/go' update_cache=yes

    - name: Install golang
      apt: name=golang

    - name: Install other packages
      apt: name={{ item }} state=latest
      with_items:
        - git
        - git-core
        - tmux
        - zsh
        - vim

    - name: install oh-my-zsh
      shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
      sudo: yes
      sudo_user: vagrant

    - name: Change default Shell
      shell: chsh -s `which zsh`
      sudo: yes
      sudo_user: vagrant

    - name: create /home/vagrant/go directory
      file: dest=/home/vagrant/go state=directory owner=vagrant group=vagrant mode=0700

    - name: Add the Gopath variable
      shell: export GOPATH=$HOME/go/project
