---
- hosts: all
  sudo: yes

  tasks:

    - name: Add the goland repo
      apt_repository: repo='ppa:gophers/go' update_cache=yes
      
    - name: Install golang
      apt: name=golang

    - name: Install other packages
      apt: name={{ item }} state=latest
      with_items:
        - git
